# EC memory layout config
# Refer to these links for help with these options
#
# https://github.com/BeardOverflow/msi-ec
# https://github.com/dmitry-s93/MControlCenter
#
# This code includes memory layouts for 17 different EC memory versions:
# https://github.com/BeardOverflow/msi-ec/blob/main/msi-ec.c
# To cross reference
[ec]
file = "/sys/kernel/debug/ec/ec0/io"

bat_limit.addr = 0xD7
cooler_boost.addr = 0x98

[ec.shift]
addr = 0xD2

[ec.shift.enum]
eco = 0xC2
comfort = 0xC1
sport = 0xC0
turbo = 0xC4

[ec.fanmode]
addr = 0xD4

[ec.fanmode.enum]
auto = 0x0D
silent = 0x1D
advanced = 0x8D


# Use 'ls /dev/cpu' to verify the amount of cores of the Intel CPU
# Don't simply use the amount of cores advertised on your system
# because of Hyperthreading and P/E-cores differences
[msr]
num_cores = 12


# The location of the NVML shared object.
# Arch Linux puts in here but your distro might put it somewhere else.
[nv]
libnvml = "/usr/lib/libnvidia-ml.so"